version: "3.3"
services:

    website:
        build:
            context: .
            dockerfile: website/Dockerfile
        environment:
            EVALUATORS_HOST: result-castle
        image: registry.internal.opgo.dk/goettcke/website:latest
        networks:
            - microservices
        ports:
            - 80:80

    result-castle:
        build:
            context: .
            dockerfile: result_castle/Dockerfile
        environment:
            RUNNERS_HOST: runner
        image: registry.internal.opgo.dk/goettcke/result-castle:latest
        networks:
            - microservices

    runner:
        build:
            context: .
            dockerfile: runner/Dockerfile
        image: registry.internal.opgo.dk/goettcke/runner:latest
        networks:
            - microservices

#    website_nginx:
#        build:
#            context: website_using_nginx/
#            dockerfile: Dockerfile
#       environment:
#            EVALUATORS_HOST: result-castle
#        image: registry.internal.opgo.dk/goettcke/website_nginx:latest
#        networks:
#           - microservices
#        volumes: 
#            - ./app:/app
#       ports:
#           - "80:80"

networks:
    microservices:

