apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: website
            port:
              number: 5000

--- 
apiVersion: v1
kind: ConfigMap
metadata: 
  name: nginx-ingress-tcp-microk8s-conf
  namespace: ingress
data: 
  80: "default/website:5000"
